<?php
namespace App\Services;
use App\Domain\Imports\{ChunkStatus,ImportStatus};use App\Models\ImportExecution;use Illuminate\Support\Facades\DB;
final class ImportFinalizer
{
 public function finalize(string $executionId):void{DB::transaction(function()use($executionId){
  $e=ImportExecution::with('import')->lockForUpdate()->findOrFail($executionId);if(in_array($e->status,[ImportStatus::Completed,ImportStatus::CompletedWithErrors,ImportStatus::Cancelled],true))return;
  if($e->cancel_requested_at){$e->update(['status'=>ImportStatus::Cancelled,'completed_at'=>now()]);return;}if($e->chunks()->whereIn('status',[ChunkStatus::Pending->value,ChunkStatus::Processing->value])->exists())return;if($e->chunks()->where('status',ChunkStatus::Failed->value)->exists()){$e->update(['status'=>ImportStatus::Failed,'completed_at'=>now()]);return;}
  [$successful,$duplicates]=$this->mergeStaging($e);$durations=$e->chunks()->whereNotNull('duration_ms')->pluck('duration_ms')->sort()->values();$dbWrites=$e->chunks()->pluck('db_write_ms')->map(fn($v)=>(int)$v)->sort()->values();$pct=fn($values,float $p)=>$values->isEmpty()?null:$values[(int)floor(($values->count()-1)*$p)];$seconds=max(.001,($e->started_at??$e->created_at)->diffInMilliseconds(now())/1000);$strategy=$e->mapping_snapshot_json['duplicate_strategy']??'keep_first';$hasErrors=$e->invalid_rows>0||$e->failed_rows>0||($strategy==='reject'&&$duplicates>0);$queueLag=max(0,(int)(($e->started_at??now())->diffInMilliseconds($e->created_at)));
  $e->update(['successful_rows'=>$successful,'duplicate_rows'=>$duplicates,'status'=>$hasErrors?ImportStatus::CompletedWithErrors:ImportStatus::Completed,'completed_at'=>now(),'metrics_json'=>['rows_per_second'=>round($e->processed_rows/$seconds,2),'queue_lag_ms'=>$queueLag,'error_rate'=>$e->processed_rows?round(($e->invalid_rows+$e->failed_rows)/$e->processed_rows,6):0,'duplicate_rate'=>$e->processed_rows?round($duplicates/$e->processed_rows,6):0,'chunk_duration_ms'=>['p50'=>$pct($durations,.5),'p95'=>$pct($durations,.95)],'db_write_ms_per_chunk'=>['p50'=>$pct($dbWrites,.5),'p95'=>$pct($dbWrites,.95)],'peak_worker_memory_bytes'=>(int)$e->chunks()->max('peak_memory_bytes'),'db_batch_size'=>(int)($e->mapping_snapshot_json['db_batch_size']??250)]]);
 },3);}
 private function mergeStaging(ImportExecution $e):array{$strategy=$e->mapping_snapshot_json['duplicate_strategy']??'keep_first';$total=(int)DB::table('import_staging_records')->where('execution_id',$e->id)->count();if($total===0)return[0,0];return match($strategy){'keep_last','upsert'=>$this->upsertRanked($e,$total),'reject'=>$this->rejectDuplicates($e,$total),default=>$this->keepFirst($e,$total)};}
 private function keepFirst(ImportExecution $e,int $total):array{$row=DB::selectOne("WITH ranked AS (SELECT s.*, row_number() over(partition by dedupe_key order by source_row_number asc) rn FROM import_staging_records s WHERE execution_id=?), inserted AS (INSERT INTO imported_records(id,organization_id,execution_id,source_row_number,dedupe_key,payload,created_at,updated_at) SELECT id,organization_id,execution_id,source_row_number,dedupe_key,payload,now(),now() FROM ranked WHERE rn=1 ON CONFLICT (organization_id,dedupe_key) DO NOTHING RETURNING 1) SELECT count(*)::int inserted FROM inserted",[$e->id]);$inserted=(int)($row->inserted??0);return[$inserted,$total-$inserted];}
 private function upsertRanked(ImportExecution $e,int $total):array{$row=DB::selectOne("WITH ranked AS (SELECT s.*, row_number() over(partition by dedupe_key order by source_row_number desc) rn FROM import_staging_records s WHERE execution_id=?), chosen AS (SELECT * FROM ranked WHERE rn=1), merged AS (INSERT INTO imported_records(id,organization_id,execution_id,source_row_number,dedupe_key,payload,created_at,updated_at) SELECT id,organization_id,execution_id,source_row_number,dedupe_key,payload,now(),now() FROM chosen ON CONFLICT (organization_id,dedupe_key) DO UPDATE SET execution_id=excluded.execution_id,source_row_number=excluded.source_row_number,payload=excluded.payload,updated_at=now() RETURNING 1) SELECT count(*)::int merged FROM merged",[$e->id]);$merged=(int)($row->merged??0);return[$merged,$total-$merged];}
 private function rejectDuplicates(ImportExecution $e,int $total):array{
  DB::statement("WITH counts AS (SELECT dedupe_key,count(*) c FROM import_staging_records WHERE execution_id=? GROUP BY dedupe_key), bad AS (SELECT s.* FROM import_staging_records s JOIN counts c USING(dedupe_key) WHERE s.execution_id=? AND (c.c>1 OR EXISTS(SELECT 1 FROM imported_records r WHERE r.organization_id=s.organization_id AND r.dedupe_key=s.dedupe_key))) INSERT INTO import_row_errors(id,execution_id,source_row_number,error_code,field,message,raw_row_json,created_at,updated_at) SELECT gen_random_uuid(),execution_id,source_row_number,'duplicate',null,'Duplicate row rejected',null,now(),now() FROM bad",[$e->id,$e->id]);
  $row=DB::selectOne("WITH counts AS (SELECT dedupe_key,count(*) c FROM import_staging_records WHERE execution_id=? GROUP BY dedupe_key), candidates AS (SELECT s.* FROM import_staging_records s JOIN counts c USING(dedupe_key) WHERE s.execution_id=? AND c.c=1 AND NOT EXISTS(SELECT 1 FROM imported_records r WHERE r.organization_id=s.organization_id AND r.dedupe_key=s.dedupe_key)), inserted AS (INSERT INTO imported_records(id,organization_id,execution_id,source_row_number,dedupe_key,payload,created_at,updated_at) SELECT id,organization_id,execution_id,source_row_number,dedupe_key,payload,now(),now() FROM candidates ON CONFLICT (organization_id,dedupe_key) DO NOTHING RETURNING 1) SELECT count(*)::int inserted FROM inserted",[$e->id,$e->id]);$inserted=(int)($row->inserted??0);return[$inserted,$total-$inserted];
 }
}
