<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {public function up():void{
Schema::create('imports',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('organization_id')->index();$t->string('name');$t->string('source_type');$t->string('storage_key');$t->string('original_filename');$t->unsignedBigInteger('file_size');$t->string('checksum',64)->index();$t->string('status')->index();$t->jsonb('source_schema_json')->nullable();$t->unsignedBigInteger('detected_row_count')->nullable();$t->timestamps();$t->foreign('organization_id')->references('id')->on('organizations')->cascadeOnDelete();});
Schema::create('import_executions',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('import_id')->index();$t->jsonb('mapping_snapshot_json');$t->string('status')->index();$t->unsignedBigInteger('total_rows')->default(0);$t->unsignedBigInteger('processed_rows')->default(0);$t->unsignedBigInteger('successful_rows')->default(0);$t->unsignedBigInteger('invalid_rows')->default(0);$t->unsignedBigInteger('duplicate_rows')->default(0);$t->unsignedBigInteger('failed_rows')->default(0);$t->timestampTz('started_at')->nullable();$t->timestampTz('completed_at')->nullable();$t->timestampTz('cancel_requested_at')->nullable();$t->timestamps();$t->foreign('import_id')->references('id')->on('imports')->cascadeOnDelete();});
Schema::create('import_chunks',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('execution_id')->index();$t->unsignedInteger('chunk_index');$t->jsonb('range_metadata_json');$t->string('status')->index();$t->unsignedInteger('attempts')->default(0);$t->unsignedInteger('processed_rows')->default(0);$t->timestamps();$t->unique(['execution_id','chunk_index']);$t->foreign('execution_id')->references('id')->on('import_executions')->cascadeOnDelete();});
Schema::create('imported_records',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('organization_id')->index();$t->uuid('execution_id')->index();$t->unsignedBigInteger('source_row_number');$t->string('dedupe_key',64);$t->unique(['organization_id','dedupe_key']);$t->jsonb('payload');$t->timestamps();$t->unique(['execution_id','source_row_number']);$t->foreign('organization_id')->references('id')->on('organizations')->cascadeOnDelete();$t->foreign('execution_id')->references('id')->on('import_executions')->cascadeOnDelete();});
Schema::create('import_row_errors',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('execution_id')->index();$t->unsignedBigInteger('source_row_number');$t->string('error_code')->index();$t->string('field')->nullable();$t->text('message');$t->jsonb('raw_row_json')->nullable();$t->timestamps();$t->foreign('execution_id')->references('id')->on('import_executions')->cascadeOnDelete();});
}public function down():void{Schema::dropIfExists('import_row_errors');Schema::dropIfExists('imported_records');Schema::dropIfExists('import_chunks');Schema::dropIfExists('import_executions');Schema::dropIfExists('imports');}};
