<?php
namespace App\Http\Controllers;
use App\Domain\Imports\{ChunkStatus,ImportStatus,RowValidator,TransformPipeline};use App\Jobs\{PlanImportExecution,ProcessImportChunk};use App\Models\{DataImport,ImportExecution};use App\Services\BuildImportSnapshot;use Illuminate\Http\{JsonResponse,Request};use Illuminate\Support\Facades\DB;use Symfony\Component\HttpFoundation\StreamedResponse;
final class ImportOperationsController
{
 public function preview(Request $r,DataImport $import,BuildImportSnapshot $builder,TransformPipeline $transforms,RowValidator $validator):JsonResponse{$this->auth($r,$import->organization_id);$snapshot=$builder->build($import);$rows=[];foreach(array_slice($import->source_schema_json['sample']??[],0,25) as $source){$mapped=[];$errors=[];try{foreach($snapshot['mappings'] as $dest=>$config)$mapped[$dest]=$transforms->apply($source[$config['source']]??null,$config['transforms']??[],$source);$errors=$validator->validate($mapped,$snapshot['validation']);}catch(\Throwable $e){$errors=[['field'=>'*','code'=>'transform_error','message'=>$e->getMessage()]];}$rows[]=['source'=>$this->sanitizePreview($source),'output'=>$this->sanitizePreview($mapped),'errors'=>$errors];}return response()->json(['rows'=>$rows,'snapshot'=>$snapshot]);}
 public function execution(Request $r,DataImport $import,ImportExecution $execution):JsonResponse{$this->auth($r,$import->organization_id);abort_unless($execution->import_id===$import->id,404);$errors=DB::table('import_row_errors')->where('execution_id',$execution->id)->selectRaw('error_code, count(*) count')->groupBy('error_code')->orderByDesc('count')->get();$chunks=$execution->chunks()->selectRaw('status,count(*) count')->groupBy('status')->get();$seconds=$execution->started_at?max(.001,$execution->started_at->diffInMilliseconds($execution->completed_at??now())/1000):null;return response()->json(['execution'=>$execution,'progress'=>['processed'=>$execution->processed_rows,'total'=>$execution->total_rows,'percent'=>$execution->total_rows?round($execution->processed_rows/$execution->total_rows*100,2):null,'rows_per_second'=>$seconds?round($execution->processed_rows/$seconds,2):0],'chunk_status'=>$chunks,'error_distribution'=>$errors]);}
 public function resume(Request $r,DataImport $import,ImportExecution $execution):JsonResponse{$this->auth($r,$import->organization_id);abort_unless($execution->import_id===$import->id,404);abort_unless(in_array($execution->status,[ImportStatus::Failed,ImportStatus::Cancelled],true),409);DB::transaction(function()use($execution){$e=ImportExecution::lockForUpdate()->findOrFail($execution->id);$e->chunks()->whereIn('status',[ChunkStatus::Failed->value,ChunkStatus::Cancelled->value,ChunkStatus::Processing->value])->update(['status'=>ChunkStatus::Pending->value,'last_error'=>null]);$e->update(['status'=>ImportStatus::Processing,'cancel_requested_at'=>null,'completed_at'=>null]);DB::afterCommit(function()use($e){if($e->chunks()->count()===0)PlanImportExecution::dispatch($e->id)->onQueue('imports-plan');else $e->chunks()->where('status',ChunkStatus::Pending->value)->pluck('id')->each(fn($id)=>ProcessImportChunk::dispatch($id)->onQueue('imports'));});},3);return response()->json(['status'=>'resume_queued'],202);}
 public function errorRows(Request $r,DataImport $import,ImportExecution $execution):JsonResponse{$this->auth($r,$import->organization_id);abort_unless($execution->import_id===$import->id,404);$rows=DB::table('import_row_errors')->where('execution_id',$execution->id)->orderBy('source_row_number')->orderBy('id')->paginate(min(100,max(1,(int)$r->integer('per_page',50))));return response()->json($rows);}
 public function errors(Request $r,DataImport $import,ImportExecution $execution):StreamedResponse{$this->auth($r,$import->organization_id);abort_unless($execution->import_id===$import->id,404);return response()->streamDownload(function()use($execution){$out=fopen('php://output','wb');fputcsv($out,['source_row_number','field','error_code','message','selected_source_values']);DB::table('import_row_errors')->where('execution_id',$execution->id)->orderBy('source_row_number')->chunkById(500,function($rows)use($out){foreach($rows as $row)fputcsv($out,[$row->source_row_number,$this->safeCsv((string)$row->field),$this->safeCsv((string)$row->error_code),$this->safeCsv((string)$row->message),$this->safeCsv((string)$row->raw_row_json)]);},'id');fclose($out);},"dataforge-errors-{$execution->id}.csv",['Content-Type'=>'text/csv; charset=UTF-8']);}
 private function safeCsv(string $value):string{return preg_match('/^[=+\-@]/',$value)?"'".$value:$value;}private function sanitizePreview(array $row):array{return array_map(fn($v)=>is_string($v)?mb_substr(strip_tags($v),0,500):$v,$row);}private function auth(Request $r,string $org):void{abort_unless($r->user()->organizations()->whereKey($org)->exists(),403);}
}
