<?php
namespace App\Http\Controllers;
use App\Domain\Imports\ImportStatus;use App\Jobs\AnalyzeImport;use App\Models\DataImport;use App\Services\{BuildImportSnapshot,FileTypeInspector,OperationalMetrics,StartImportExecution};use Illuminate\Http\{JsonResponse,Request};use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;
final class ImportController
{
 public function index(Request $r):JsonResponse{$ids=$r->user()->organizations()->pluck('organizations.id');return response()->json(DataImport::whereIn('organization_id',$ids)->with('destinationSchema')->latest()->paginate(min(100,max(1,$r->integer('per_page',50)))));}
 public function show(Request $r,DataImport $import):JsonResponse{$this->auth($r,$import->organization_id);return response()->json($import->load('destinationSchema.fields','mappings.field','executions'));}
 public function store(Request $r,FileTypeInspector $inspector,OperationalMetrics $metrics):JsonResponse{$d=$r->validate(['organization_id'=>'required|uuid','file'=>'required|file|max:524288','name'=>'required|string|max:120','source_type'=>'required|in:csv,xlsx,ndjson','sheet_index'=>'nullable|integer|min:0','retention_days'=>'nullable|integer|min:1|max:3650']);$this->auth($r,$d['organization_id']);$file=$d['file'];$stream=fopen($file->getRealPath(),'rb');try{$meta=$inspector->assertMatches($stream,$d['source_type']);}finally{fclose($stream);}$key="organizations/{$d['organization_id']}/imports/".Str::uuid().'.'.$inspector->extensionFor($d['source_type']);try{Storage::putFileAs(dirname($key),$file,basename($key));}catch(\Throwable $e){$metrics->storageFailure($d['organization_id']);throw $e;}$import=DataImport::create(['organization_id'=>$d['organization_id'],'name'=>$d['name'],'source_type'=>$d['source_type'],'storage_key'=>$key,'original_filename'=>$file->getClientOriginalName(),'file_size'=>$file->getSize(),'checksum'=>hash_file('sha256',$file->getRealPath()),'status'=>ImportStatus::Analyzing,'source_options_json'=>array_filter(['sheet_index'=>$d['sheet_index']??null,'detected_mime'=>$meta['mime']]),'retention_until'=>isset($d['retention_days'])?now()->addDays((int)$d['retention_days']):null]);AnalyzeImport::dispatch($import->id)->onQueue('imports-analyze');return response()->json($import,202);}
 public function execute(Request $r,DataImport $import,BuildImportSnapshot $builder,StartImportExecution $starter):JsonResponse{$this->auth($r,$import->organization_id);abort_unless($import->destination_schema_id&&$import->mappings()->exists(),422);$d=$r->validate(['chunk_size'=>'integer|min:100|max:10000']);return response()->json($starter->start($import,$builder->build($import),(int)($d['chunk_size']??2000)),202);}
 public function cancel(Request $r,DataImport $import,string $executionId):JsonResponse{$this->auth($r,$import->organization_id);$execution=$import->executions()->findOrFail($executionId);$execution->update(['cancel_requested_at'=>now()]);return response()->json(['status'=>'cancellation_requested']);}
 public function destroy(Request $r,DataImport $import,OperationalMetrics $metrics):JsonResponse{$this->auth($r,$import->organization_id);abort_if($import->executions()->whereIn('status',['queued','processing'])->exists(),409,'Cannot delete an active import');try{Storage::disk(config('filesystems.default'))->delete($import->storage_key);}catch(\Throwable $e){$metrics->storageFailure($import->organization_id);throw $e;}$import->delete();return response()->json(['deleted'=>true]);}
 private function auth(Request $r,string $org):void{abort_unless($r->user()->organizations()->whereKey($org)->exists(),403);}
}
