<?php
namespace App\Http\Controllers;
use App\Domain\Imports\TransformPipeline;use App\Models\{DataImport,DestinationSchema,ImportMapping};use Illuminate\Http\{JsonResponse,Request};use Illuminate\Support\Facades\DB;
final class MappingController
{
 public function show(Request $r,DataImport $import):JsonResponse{$this->auth($r,$import->organization_id);return response()->json(['destination_schema'=>$import->destinationSchema?->load('fields'),'mappings'=>$import->mappings()->with('field')->get(),'policy'=>$import->import_policy_json]);}
 public function save(Request $r,DataImport $import,TransformPipeline $transforms):JsonResponse{$this->auth($r,$import->organization_id);$d=$r->validate(['destination_schema_id'=>'required|uuid','mappings'=>'required|array','mappings.*.destination_field_id'=>'required|uuid','mappings.*.source_column'=>'nullable|string|max:255','mappings.*.transforms'=>'array','validation'=>'array','dedupe_fields'=>'array|min:1','duplicate_strategy'=>'in:keep_first,keep_last,reject,upsert','db_batch_size'=>'integer|min:50|max:1000','error_source_fields'=>'array']);$schema=DestinationSchema::whereKey($d['destination_schema_id'])->where('organization_id',$import->organization_id)->with('fields')->firstOrFail();$fieldIds=$schema->fields->pluck('id')->all();$headers=$import->source_schema_json['headers']??[];foreach($d['mappings'] as $m){abort_unless(in_array($m['destination_field_id'],$fieldIds,true),422);if($m['source_column']!==null)abort_unless(in_array($m['source_column'],$headers,true),422);$transforms->validateConfig($m['transforms']??[]);}DB::transaction(function()use($import,$schema,$d){$import->update(['destination_schema_id'=>$schema->id,'import_policy_json'=>['validation'=>$d['validation']??[],'dedupe_fields'=>$d['dedupe_fields'],'duplicate_strategy'=>$d['duplicate_strategy']??'keep_first','db_batch_size'=>$d['db_batch_size']??250,'error_source_fields'=>$d['error_source_fields']??[]]]);foreach($d['mappings'] as $m)ImportMapping::updateOrCreate(['import_id'=>$import->id,'destination_field_id'=>$m['destination_field_id']],['source_column'=>$m['source_column'],'transform_pipeline_json'=>$m['transforms']??[]]);},3);return response()->json(['saved'=>true,'mapping'=>$this->snapshot($import->fresh())]);}
 public function snapshot(DataImport $import):array{$import->load('mappings.field');$mappings=[];foreach($import->mappings as $m)$mappings[$m->field->key]=['source'=>$m->source_column,'transforms'=>$m->transform_pipeline_json??[]];return ['mappings'=>$mappings,...($import->import_policy_json??[])];}
 private function auth(Request $r,string $org):void{abort_unless($r->user()->organizations()->whereKey($org)->exists(),403);}
}
