<?php
namespace App\Http\Controllers;
use App\Domain\Imports\ImportStatus;use App\Jobs\AnalyzeImport;use App\Models\DataImport;use App\Services\{FileTypeInspector,OperationalMetrics};use Illuminate\Http\{JsonResponse,Request};use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;
final class UploadController
{
 public function prepare(Request $r,FileTypeInspector $inspector,OperationalMetrics $metrics):JsonResponse{$d=$r->validate(['organization_id'=>'required|uuid','filename'=>'required|string|max:255','file_size'=>'required|integer|min:1|max:5368709120','source_type'=>'required|in:csv,xlsx,ndjson','content_type'=>'nullable|string|max:120']);$this->auth($r,$d['organization_id']);$key="organizations/{$d['organization_id']}/imports/".Str::uuid().'.'.$inspector->extensionFor($d['source_type']);$disk=Storage::disk(config('filesystems.default'));if(!method_exists($disk,'temporaryUploadUrl'))return response()->json(['error'=>['code'=>'presigned_upload_not_supported','message'=>'Use the direct upload endpoint for this storage driver']],409);try{$signed=$disk->temporaryUploadUrl($key,now()->addMinutes(20),['ContentType'=>$d['content_type']??'application/octet-stream']);}catch(\Throwable $e){$metrics->storageFailure($d['organization_id']);throw $e;}return response()->json(['storage_key'=>$key,'upload'=>$signed,'expires_in_seconds'=>1200]);}
 public function finalize(Request $r,FileTypeInspector $inspector,OperationalMetrics $metrics):JsonResponse{$d=$r->validate(['organization_id'=>'required|uuid','name'=>'required|string|max:120','storage_key'=>'required|string|max:1024','original_filename'=>'required|string|max:255','source_type'=>'required|in:csv,xlsx,ndjson','sheet_index'=>'nullable|integer|min:0','retention_days'=>'nullable|integer|min:1|max:3650']);$this->auth($r,$d['organization_id']);abort_unless(str_starts_with($d['storage_key'],"organizations/{$d['organization_id']}/imports/"),422);$disk=Storage::disk(config('filesystems.default'));try{abort_unless($disk->exists($d['storage_key']),404);$size=$disk->size($d['storage_key']);abort_if($size<=0||$size>5*1024*1024*1024,413);$stream=$disk->readStream($d['storage_key']);}catch(\Throwable $e){$metrics->storageFailure($d['organization_id']);throw $e;}try{$meta=$inspector->assertMatches($stream,$d['source_type']);}finally{if(is_resource($stream))fclose($stream);}try{$stream=$disk->readStream($d['storage_key']);}catch(\Throwable $e){$metrics->storageFailure($d['organization_id']);throw $e;}$hash=hash_init('sha256');try{while(!feof($stream)){hash_update($hash,fread($stream,1024*1024)?:'');}$checksum=hash_final($hash);}finally{if(is_resource($stream))fclose($stream);}$import=DataImport::create(['organization_id'=>$d['organization_id'],'name'=>$d['name'],'source_type'=>$d['source_type'],'storage_key'=>$d['storage_key'],'original_filename'=>$d['original_filename'],'file_size'=>$size,'checksum'=>$checksum,'status'=>ImportStatus::Analyzing,'source_options_json'=>array_filter(['sheet_index'=>$d['sheet_index']??null,'detected_mime'=>$meta['mime']]),'retention_until'=>isset($d['retention_days'])?now()->addDays((int)$d['retention_days']):null]);AnalyzeImport::dispatch($import->id)->onQueue('imports-analyze');return response()->json($import,202);}
 private function auth(Request $r,string $org):void{abort_unless($r->user()->organizations()->whereKey($org)->exists(),403);}
}
