<?php
namespace App\Domain\Imports;
use DateTimeImmutable;use InvalidArgumentException;
final class TransformPipeline
{
 /** @param list<array{type:string,config?:array<string,mixed>}> $pipeline */
 public function validateConfig(array $pipeline):void{foreach($pipeline as $i=>$stage){$type=$stage['type']??'';if(!in_array($type,['trim','lower','upper','normalize_whitespace','default','parse_number','parse_date','normalize_phone','regex_replace','map','concat','split'],true))throw new InvalidArgumentException("Unknown transform at {$i}: {$type}");if($type==='regex_replace'&&empty($stage['config']['pattern']))throw new InvalidArgumentException('regex_replace requires pattern');if($type==='split'&&!array_key_exists('index',$stage['config']??[]))throw new InvalidArgumentException('split requires index');}}
 public function apply(mixed $value,array $pipeline,array $row=[]):mixed{$this->validateConfig($pipeline);foreach($pipeline as $stage){$type=$stage['type'];$c=$stage['config']??[];$value=match($type){
  'trim'=>is_string($value)?trim($value):$value,'lower'=>is_string($value)?$this->lower($value):$value,'upper'=>is_string($value)?$this->upper($value):$value,'normalize_whitespace'=>is_string($value)?preg_replace('/\s+/u',' ',trim($value)):$value,
  'default'=>(($value===null||$value==='')?($c['value']??null):$value),'parse_number'=>$this->parseNumber($value),'parse_date'=>$this->parseDate($value,$c),'normalize_phone'=>$this->normalizePhone($value,$c),'regex_replace'=>$this->regexReplace($value,$c),'map'=>$c['values'][(string)$value]??($c['default']??$value),'concat'=>$this->concat($value,$c,$row),'split'=>$this->split($value,$c),default=>$value};}return $value;}
 private function parseNumber(mixed $v):int|float|null{if($v===null||$v==='')return null;$clean=preg_replace('/[^0-9.\-]/','',(string)$v);if($clean===''||!is_numeric($clean))throw new InvalidArgumentException('Value is not numeric');return str_contains($clean,'.')?(float)$clean:(int)$clean;}
 private function parseDate(mixed $v,array $c):?string{if($v===null||$v==='')return null;$input=$c['input_format']??null;$out=$c['output_format']??'Y-m-d';$date=$input?DateTimeImmutable::createFromFormat($input,(string)$v):new DateTimeImmutable((string)$v);if(!$date)throw new InvalidArgumentException('Value is not a valid date');return $date->format($out);}
 private function normalizePhone(mixed $v,array $c):?string{if($v===null||$v==='')return null;$raw=preg_replace('/[^0-9+]/','',(string)$v);if(str_starts_with($raw,'00'))$raw='+'.substr($raw,2);if(!str_starts_with($raw,'+')&&!empty($c['default_country_code']))$raw='+'.preg_replace('/\D/','',(string)$c['default_country_code']).ltrim($raw,'0');if(!preg_match('/^\+?[0-9]{7,15}$/',$raw))throw new InvalidArgumentException('Value is not a valid phone number');return $raw;}
 private function regexReplace(mixed $v,array $c):mixed{if(!is_string($v))return $v;$pattern=(string)($c['pattern']??'');if(@preg_match($pattern,'')===false)throw new InvalidArgumentException('regex_replace contains invalid pattern');return preg_replace($pattern,(string)($c['replacement']??''),$v);}
 private function concat(mixed $v,array $c,array $row):string{$parts=[];foreach($c['columns']??[] as $col)$parts[]=(string)($row[$col]??'');if($c['include_value']??false)array_unshift($parts,(string)$v);return implode((string)($c['separator']??' '),$parts);}
 private function split(mixed $v,array $c):mixed{if(!is_string($v))return $v;$parts=explode((string)($c['delimiter']??','),$v);return $parts[(int)$c['index']]??($c['default']??null);}
 private function lower(string $v):string{return function_exists('mb_strtolower')?mb_strtolower($v):strtolower($v);}private function upper(string $v):string{return function_exists('mb_strtoupper')?mb_strtoupper($v):strtoupper($v);}
}
